apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argo
spec:
  destination:
    namespace: decapod-db
    server: https://kubernetes.default.svc
  project: decapod-controller
  source:
    path: ${DECAPOD_SITE_NAME}/decapod-controller/postgresql
    repoURL: ${DECAPOD_MANIFESTS_GIT_REPO_URL}
    targetRevision: ${GIT_REVISION}
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: true
      prune: true
